from typing import Literal, TypeAlias

Industry: TypeAlias = Literal[
    "advertising agencies",
    "aerospace & defense",
    "agricultural inputs",
    "airlines",
    "airports & air services",
    "aluminum",
    "apparel manufacturing",
    "apparel retail",
    "asset management",
    "auto & truck dealerships",
    "auto manufacturers",
    "auto parts",
    "banks - diversified",
    "banks - regional",
    "beverages - brewers",
    "beverages - non-alcoholic",
    "beverages - wineries & distilleries",
    "biotechnology",
    "broadcasting",
    "building materials",
    "building products & equipment",
    "business equipment & supplies",
    "capital markets",
    "chemicals",
    "coking coal",
    "communication equipment",
    "computer hardware",
    "confectioners",
    "conglomerates",
    "consulting services",
    "consumer electronics",
    "copper",
    "credit services",
    "department stores",
    "diagnostics & research",
    "discount stores",
    "drug manufacturers - general",
    "drug manufacturers - specialty & generic",
    "education & training services",
    "electrical equipment & parts",
    "electronic components",
    "electronic gaming & multimedia",
    "electronics & computer distribution",
    "engineering & construction",
    "entertainment",
    "farm & heavy construction machinery",
    "farm products",
    "financial conglomerates",
    "financial data & stock exchanges",
    "food distribution",
    "footwear & accessories",
    "furnishings, fixtures & appliances",
    "gambling",
    "gold",
    "grocery stores",
    "health information services",
    "healthcare plans",
    "home improvement retail",
    "household & personal products",
    "industrial distribution",
    "information technology services",
    "infrastructure operations",
    "insurance - diversified",
    "insurance - life",
    "insurance - property & casualty",
    "insurance - reinsurance",
    "insurance - specialty",
    "insurance brokers",
    "integrated freight & logistics",
    "internet content & information",
    "internet retail",
    "leisure",
    "lodging",
    "lumber & wood production",
    "luxury goods",
    "marine shipping",
    "medical care facilities",
    "medical devices",
    "medical distribution",
    "medical instruments & supplies",
    "metal fabrication",
    "mortgage finance",
    "oil & gas drilling",
    "oil & gas e&p",
    "oil & gas equipment & services",
    "oil & gas integrated",
    "oil & gas midstream",
    "oil & gas refining & marketing",
    "other industrial metals & mining",
    "other precious metals & mining",
    "packaged foods",
    "packaging & containers",
    "paper & paper products",
    "personal services",
    "pharmaceutical retailers",
    "pollution & treatment controls",
    "publishing",
    "railroads",
    "real estate - development",
    "real estate - diversified",
    "real estate services",
    "recreational vehicles",
    "reit - diversified",
    "reit - healthcare facilities",
    "reit - hotel & motel",
    "reit - industrial",
    "reit - mortgage",
    "reit - office",
    "reit - residential",
    "reit - retail",
    "reit - specialty",
    "rental & leasing services",
    "residential construction",
    "resorts & casinos",
    "restaurants",
    "scientific & technical instruments",
    "security & protection services",
    "semiconductor equipment & materials",
    "semiconductors",
    "shell companies",
    "silver",
    "software - application",
    "software - infrastructure",
    "solar",
    "specialty business services",
    "specialty chemicals",
    "specialty industrial machinery",
    "specialty retail",
    "staffing & employment services",
    "steel",
    "telecom services",
    "textile manufacturing",
    "thermal coal",
    "tobacco",
    "tools & accessories",
    "travel services",
    "trucking",
    "uranium",
    "utilities - diversified",
    "utilities - independent power producers",
    "utilities - regulated electric",
    "utilities - regulated gas",
    "utilities - regulated water",
    "utilities - renewable",
    "waste management",
]
"""Financial market industry within a sector as categorised by yfinance."""
