from alpha_research_framework.universe.equity_data.sector.industry import (
    Industry,
)
from alpha_research_framework.universe.equity_data.sector.sector import Sector

INDUSTRIES_PER_SECTOR: dict[Sector, set[Industry]] = {
    "basic materials": {
        "coking coal",
        "other industrial metals & mining",
        "other precious metals & mining",
        "building materials",
        "steel",
        "agricultural inputs",
        "copper",
        "silver",
        "aluminum",
        "chemicals",
        "lumber & wood production",
        "specialty chemicals",
        "gold",
        "paper & paper products",
    },
    "communication services": {
        "internet content & information",
        "electronic gaming & multimedia",
        "entertainment",
        "broadcasting",
        "telecom services",
        "advertising agencies",
        "publishing",
    },
    "consumer cyclical": {
        "luxury goods",
        "recreational vehicles",
        "specialty retail",
        "personal services",
        "department stores",
        "auto manufacturers",
        "auto parts",
        "travel services",
        "restaurants",
        "resorts & casinos",
        "apparel manufacturing",
        "furnishings, fixtures & appliances",
        "residential construction",
        "apparel retail",
        "internet retail",
        "leisure",
        "packaging & containers",
        "footwear & accessories",
        "auto & truck dealerships",
        "lodging",
        "gambling",
        "home improvement retail",
        "textile manufacturing",
    },
    "consumer defensive": {
        "discount stores",
        "education & training services",
        "beverages - brewers",
        "beverages - wineries & distilleries",
        "beverages - non-alcoholic",
        "farm products",
        "grocery stores",
        "household & personal products",
        "tobacco",
        "packaged foods",
        "food distribution",
        "confectioners",
    },
    "energy": {
        "oil & gas drilling",
        "oil & gas e&p",
        "thermal coal",
        "oil & gas equipment & services",
        "uranium",
        "oil & gas integrated",
        "oil & gas midstream",
        "oil & gas refining & marketing",
    },
    "financial services": {
        "banks - regional",
        "insurance - diversified",
        "asset management",
        "banks - diversified",
        "insurance - specialty",
        "insurance brokers",
        "financial conglomerates",
        "insurance - reinsurance",
        "financial data & stock exchanges",
        "insurance - life",
        "shell companies",
        "credit services",
        "insurance - property & casualty",
        "mortgage finance",
        "capital markets",
    },
    "healthcare": {
        "pharmaceutical retailers",
        "health information services",
        "medical devices",
        "biotechnology",
        "drug manufacturers - specialty & generic",
        "medical care facilities",
        "medical distribution",
        "medical instruments & supplies",
        "healthcare plans",
        "drug manufacturers - general",
        "diagnostics & research",
    },
    "industrials": {
        "rental & leasing services",
        "railroads",
        "engineering & construction",
        "staffing & employment services",
        "airlines",
        "security & protection services",
        "integrated freight & logistics",
        "marine shipping",
        "business equipment & supplies",
        "specialty industrial machinery",
        "waste management",
        "tools & accessories",
        "aerospace & defense",
        "metal fabrication",
        "consulting services",
        "airports & air services",
        "trucking",
        "specialty business services",
        "building products & equipment",
        "electrical equipment & parts",
        "farm & heavy construction machinery",
        "conglomerates",
        "industrial distribution",
        "infrastructure operations",
        "pollution & treatment controls",
    },
    "real estate": {
        "reit - healthcare facilities",
        "real estate - development",
        "reit - industrial",
        "real estate services",
        "reit - mortgage",
        "reit - retail",
        "reit - specialty",
        "reit - diversified",
        "reit - office",
        "reit - hotel & motel",
        "real estate - diversified",
        "reit - residential",
    },
    "technology": {
        "computer hardware",
        "software - infrastructure",
        "software - application",
        "solar",
        "semiconductors",
        "communication equipment",
        "information technology services",
        "consumer electronics",
        "electronics & computer distribution",
        "electronic components",
        "semiconductor equipment & materials",
        "scientific & technical instruments",
    },
    "utilities": {
        "utilities - independent power producers",
        "utilities - diversified",
        "utilities - renewable",
        "utilities - regulated electric",
        "utilities - regulated water",
        "utilities - regulated gas",
    },
}
